version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: dotnet/sdk
        update-types:
          - version-update:semver-major
      - dependency-name: dotnet/aspnet
        update-types:
          - version-update:semver-major
