// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Database.Context;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(SaraDbContext))]
    [Migration("20251222121546_AddThermalReadingAnalysis")]
    partial class AddThermalReadingAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Database.Models.AnalysisMapping", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("AnalysesToBeRun")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("InspectionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Tag", "InspectionDescription")
                        .IsUnique();

                    b.ToTable("AnalysisMapping");
                });

            modelBuilder.Entity("api.Database.Models.Anonymization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsPersonInImage")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Anonymization");
                });

            modelBuilder.Entity("api.Database.Models.CLOEAnalysis", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("OilLevel")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CLOEAnalysis");
                });

            modelBuilder.Entity("api.Database.Models.FencillaAnalysis", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsBreak")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FencillaAnalysis");
                });

            modelBuilder.Entity("api.Database.Models.PlantData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AnonymizationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CLOEAnalysisId")
                        .HasColumnType("text");

                    b.Property<string>("Coordinates")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FencillaAnalysisId")
                        .HasColumnType("text");

                    b.Property<string>("InspectionDescription")
                        .HasColumnType("text");

                    b.Property<string>("InspectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstallationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<string>("ThermalReadingAnalysisId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnonymizationId");

                    b.HasIndex("CLOEAnalysisId");

                    b.HasIndex("FencillaAnalysisId");

                    b.HasIndex("ThermalReadingAnalysisId");

                    b.ToTable("PlantData");
                });

            modelBuilder.Entity("api.Database.Models.ThermalReadingAnalysis", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ThermalReading");
                });

            modelBuilder.Entity("api.Database.Models.Anonymization", b =>
                {
                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "DestinationBlobStorageLocation", b1 =>
                        {
                            b1.Property<string>("AnonymizationId")
                                .HasColumnType("text");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnonymizationId");

                            b1.ToTable("Anonymization");

                            b1.WithOwner()
                                .HasForeignKey("AnonymizationId");
                        });

                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "SourceBlobStorageLocation", b1 =>
                        {
                            b1.Property<string>("AnonymizationId")
                                .HasColumnType("text");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnonymizationId");

                            b1.ToTable("Anonymization");

                            b1.WithOwner()
                                .HasForeignKey("AnonymizationId");
                        });

                    b.Navigation("DestinationBlobStorageLocation")
                        .IsRequired();

                    b.Navigation("SourceBlobStorageLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("api.Database.Models.CLOEAnalysis", b =>
                {
                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "DestinationBlobStorageLocation", b1 =>
                        {
                            b1.Property<string>("CLOEAnalysisId")
                                .HasColumnType("text");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CLOEAnalysisId");

                            b1.ToTable("CLOEAnalysis");

                            b1.WithOwner()
                                .HasForeignKey("CLOEAnalysisId");
                        });

                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "SourceBlobStorageLocation", b1 =>
                        {
                            b1.Property<string>("CLOEAnalysisId")
                                .HasColumnType("text");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CLOEAnalysisId");

                            b1.ToTable("CLOEAnalysis");

                            b1.WithOwner()
                                .HasForeignKey("CLOEAnalysisId");
                        });

                    b.Navigation("DestinationBlobStorageLocation")
                        .IsRequired();

                    b.Navigation("SourceBlobStorageLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("api.Database.Models.FencillaAnalysis", b =>
                {
                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "DestinationBlobStorageLocation", b1 =>
                        {
                            b1.Property<string>("FencillaAnalysisId")
                                .HasColumnType("text");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FencillaAnalysisId");

                            b1.ToTable("FencillaAnalysis");

                            b1.WithOwner()
                                .HasForeignKey("FencillaAnalysisId");
                        });

                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "SourceBlobStorageLocation", b1 =>
                        {
                            b1.Property<string>("FencillaAnalysisId")
                                .HasColumnType("text");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FencillaAnalysisId");

                            b1.ToTable("FencillaAnalysis");

                            b1.WithOwner()
                                .HasForeignKey("FencillaAnalysisId");
                        });

                    b.Navigation("DestinationBlobStorageLocation")
                        .IsRequired();

                    b.Navigation("SourceBlobStorageLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("api.Database.Models.PlantData", b =>
                {
                    b.HasOne("api.Database.Models.Anonymization", "Anonymization")
                        .WithMany()
                        .HasForeignKey("AnonymizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Database.Models.CLOEAnalysis", "CLOEAnalysis")
                        .WithMany()
                        .HasForeignKey("CLOEAnalysisId");

                    b.HasOne("api.Database.Models.FencillaAnalysis", "FencillaAnalysis")
                        .WithMany()
                        .HasForeignKey("FencillaAnalysisId");

                    b.HasOne("api.Database.Models.ThermalReadingAnalysis", "ThermalReadingAnalysis")
                        .WithMany()
                        .HasForeignKey("ThermalReadingAnalysisId");

                    b.Navigation("Anonymization");

                    b.Navigation("CLOEAnalysis");

                    b.Navigation("FencillaAnalysis");

                    b.Navigation("ThermalReadingAnalysis");
                });

            modelBuilder.Entity("api.Database.Models.ThermalReadingAnalysis", b =>
                {
                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "DestinationBlobStorageLocation", b1 =>
                        {
                            b1.Property<string>("ThermalReadingAnalysisId")
                                .HasColumnType("text");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ThermalReadingAnalysisId");

                            b1.ToTable("ThermalReading");

                            b1.WithOwner()
                                .HasForeignKey("ThermalReadingAnalysisId");
                        });

                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "SourceBlobStorageLocation", b1 =>
                        {
                            b1.Property<string>("ThermalReadingAnalysisId")
                                .HasColumnType("text");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ThermalReadingAnalysisId");

                            b1.ToTable("ThermalReading");

                            b1.WithOwner()
                                .HasForeignKey("ThermalReadingAnalysisId");
                        });

                    b.Navigation("DestinationBlobStorageLocation")
                        .IsRequired();

                    b.Navigation("SourceBlobStorageLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
