// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Database.Context;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(SaraDbContext))]
    [Migration("20260603125924_AddSkippedStatusAndSkipReason")]
    partial class AddSkippedStatusAndSkipReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalysisInspectionRecord", b =>
                {
                    b.Property<Guid>("AnalysesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InspectionRecordsId")
                        .HasColumnType("uuid");

                    b.HasKey("AnalysesId", "InspectionRecordsId");

                    b.HasIndex("InspectionRecordsId");

                    b.ToTable("AnalysisInspectionRecord");
                });

            modelBuilder.Entity("api.Database.Models.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisGroupId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("api.Database.Models.AnalysisGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExpectedSize")
                        .HasColumnType("integer");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeoutAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("AnalysisGroups");
                });

            modelBuilder.Entity("api.Database.Models.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RunNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SkipReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("AnalysisRuns");
                });

            modelBuilder.Entity("api.Database.Models.InspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionDescription")
                        .HasColumnType("text");

                    b.Property<string>("InspectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InspectionType")
                        .HasColumnType("text");

                    b.Property<string>("InstallationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RobotName")
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisGroupId");

                    b.HasIndex("InspectionId")
                        .IsUnique();

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_InspectionRecord_CreatedAt_Id_Desc");

                    b.ToTable("InspectionRecords");
                });

            modelBuilder.Entity("api.Database.Models.ThermalReferenceMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstallationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstallationCode", "TagId", "InspectionDescription")
                        .IsUnique();

                    b.ToTable("ThermalReferenceMetadata");
                });

            modelBuilder.Entity("api.Database.Models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("AnalysisInspectionRecord", b =>
                {
                    b.HasOne("api.Database.Models.Analysis", null)
                        .WithMany()
                        .HasForeignKey("AnalysesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Database.Models.InspectionRecord", null)
                        .WithMany()
                        .HasForeignKey("InspectionRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Database.Models.Analysis", b =>
                {
                    b.HasOne("api.Database.Models.AnalysisGroup", "AnalysisGroup")
                        .WithMany("Analyses")
                        .HasForeignKey("AnalysisGroupId");

                    b.Navigation("AnalysisGroup");
                });

            modelBuilder.Entity("api.Database.Models.AnalysisRun", b =>
                {
                    b.HasOne("api.Database.Models.Analysis", "Analysis")
                        .WithMany("Runs")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("api.Database.Models.InspectionRecord", b =>
                {
                    b.HasOne("api.Database.Models.AnalysisGroup", "AnalysisGroup")
                        .WithMany("InspectionRecords")
                        .HasForeignKey("AnalysisGroupId");

                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "BlobStorageLocation", b1 =>
                        {
                            b1.Property<Guid>("InspectionRecordId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InspectionRecordId");

                            b1.ToTable("InspectionRecords");

                            b1.WithOwner()
                                .HasForeignKey("InspectionRecordId");
                        });

                    b.OwnsOne("api.Database.Models.Position", "TargetPosition", b1 =>
                        {
                            b1.Property<Guid>("InspectionRecordId")
                                .HasColumnType("uuid");

                            b1.Property<float>("X")
                                .HasColumnType("real")
                                .HasJsonPropertyName("x");

                            b1.Property<float>("Y")
                                .HasColumnType("real")
                                .HasJsonPropertyName("y");

                            b1.Property<float>("Z")
                                .HasColumnType("real")
                                .HasJsonPropertyName("z");

                            b1.HasKey("InspectionRecordId");

                            b1.ToTable("InspectionRecords");

                            b1.WithOwner()
                                .HasForeignKey("InspectionRecordId");
                        });

                    b.OwnsOne("api.Database.Models.Pose", "RobotPose", b1 =>
                        {
                            b1.Property<Guid>("InspectionRecordId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean");

                            b1.HasKey("InspectionRecordId");

                            b1.ToTable("InspectionRecords");

                            b1.WithOwner()
                                .HasForeignKey("InspectionRecordId");

                            b1.OwnsOne("api.Database.Models.Orientation", "Orientation", b2 =>
                                {
                                    b2.Property<Guid>("PoseInspectionRecordId")
                                        .HasColumnType("uuid");

                                    b2.Property<float>("W")
                                        .HasColumnType("real")
                                        .HasJsonPropertyName("w");

                                    b2.Property<float>("X")
                                        .HasColumnType("real")
                                        .HasJsonPropertyName("x");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real")
                                        .HasJsonPropertyName("y");

                                    b2.Property<float>("Z")
                                        .HasColumnType("real")
                                        .HasJsonPropertyName("z");

                                    b2.HasKey("PoseInspectionRecordId");

                                    b2.ToTable("InspectionRecords");

                                    b2.HasJsonPropertyName("orientation");

                                    b2.WithOwner()
                                        .HasForeignKey("PoseInspectionRecordId");
                                });

                            b1.OwnsOne("api.Database.Models.Position", "Position", b2 =>
                                {
                                    b2.Property<Guid>("PoseInspectionRecordId")
                                        .HasColumnType("uuid");

                                    b2.Property<float>("X")
                                        .HasColumnType("real")
                                        .HasJsonPropertyName("x");

                                    b2.Property<float>("Y")
                                        .HasColumnType("real")
                                        .HasJsonPropertyName("y");

                                    b2.Property<float>("Z")
                                        .HasColumnType("real")
                                        .HasJsonPropertyName("z");

                                    b2.HasKey("PoseInspectionRecordId");

                                    b2.ToTable("InspectionRecords");

                                    b2.HasJsonPropertyName("position");

                                    b2.WithOwner()
                                        .HasForeignKey("PoseInspectionRecordId");
                                });

                            b1.Navigation("Orientation")
                                .IsRequired();

                            b1.Navigation("Position")
                                .IsRequired();
                        });

                    b.Navigation("AnalysisGroup");

                    b.Navigation("BlobStorageLocation")
                        .IsRequired();

                    b.Navigation("RobotPose");

                    b.Navigation("TargetPosition");
                });

            modelBuilder.Entity("api.Database.Models.ThermalReferenceMetadata", b =>
                {
                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "ReferenceImageBlobStorageLocation", b1 =>
                        {
                            b1.Property<Guid>("ThermalReferenceMetadataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ThermalReferenceMetadataId");

                            b1.ToTable("ThermalReferenceMetadata");

                            b1.WithOwner()
                                .HasForeignKey("ThermalReferenceMetadataId");
                        });

                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "ReferencePolygonBlobStorageLocation", b1 =>
                        {
                            b1.Property<Guid>("ThermalReferenceMetadataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ThermalReferenceMetadataId");

                            b1.ToTable("ThermalReferenceMetadata");

                            b1.WithOwner()
                                .HasForeignKey("ThermalReferenceMetadataId");
                        });

                    b.Navigation("ReferenceImageBlobStorageLocation")
                        .IsRequired();

                    b.Navigation("ReferencePolygonBlobStorageLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("api.Database.Models.Workflow", b =>
                {
                    b.HasOne("api.Database.Models.AnalysisRun", "AnalysisRun")
                        .WithMany("Workflows")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("api.Database.Models.BlobStorageLocation", "InputBlobStorageLocations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("WorkflowId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkflowId");

                            b1.ToTable("Workflows_InputBlobStorageLocations");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowId");
                        });

                    b.OwnsOne("api.Database.Models.BlobStorageLocation", "OutputBlobStorageLocation", b1 =>
                        {
                            b1.Property<Guid>("WorkflowId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BlobContainer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StorageAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WorkflowId");

                            b1.ToTable("Workflows");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowId");
                        });

                    b.Navigation("AnalysisRun");

                    b.Navigation("InputBlobStorageLocations");

                    b.Navigation("OutputBlobStorageLocation");
                });

            modelBuilder.Entity("api.Database.Models.Analysis", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("api.Database.Models.AnalysisGroup", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("InspectionRecords");
                });

            modelBuilder.Entity("api.Database.Models.AnalysisRun", b =>
                {
                    b.Navigation("Workflows");
                });
#pragma warning restore 612, 618
        }
    }
}
