name: Api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Build project and dependencies
        working-directory: ./api
        run: dotnet build

  test_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build project and dependencies
        working-directory: ./api.Tests
        run: dotnet build -warnaserror

      - name: Run tests
        working-directory: ./api.Tests
        run: dotnet test

  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Run csharpier format
        working-directory: ./api
        run: |
          dotnet tool restore
          dotnet csharpier . --check
