name: Run database migrations (Development)

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  run_migrations:
    name: Update database in Development
    if: ${{ vars.SARA_DEV_MIGRATIONS_IN_ARGOCD != 'true' }}
    uses: equinor/armada/.github/workflows/run_dotnet_migrations.yml@main
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    with:
      environment: Development
      working_directory: api
      azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      use_app_reg_identity: ${{ vars.SARA_DEV_MIGRATIONS_USE_APP_REG_IDENTITY == 'true' }}
