name: Verify migrations

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read
  issues: read

jobs:
  verify_migrations:
    uses: equinor/armada/.github/workflows/verify_migrations.yml@main
    with:
      database_paths: "api/Database/**"
      migrations_paths: "api/Migrations/**"
